### ISSUE TITLE
Communication Error

### ISSUE THREAD

**Issue by sleepydunsparce** [supremetakoyaki/ShiverBot#1]
Hi! I successfully connected to my switch with Shiverbot. I also see the amount I edited before purchasing a drink or adding abilities with murch. However, once I press purchase, the game tries to save and gives me a communication error. What should I do to mitigate this issue?

**Comment by supremetakoyaki** [comment]
hi! what did you edit?
buy a gacha capsule and/or scrub gear to save the changes without getting a communication error. do not enter any shop until the game saves.
