### ISSUE TITLE
Add Super-Sea-Shells

### ISSUE THREAD

**Issue by iAroc** [supremetakoyaki/ShiverBot#2]
Heyya

Could you add Super-Sea-Shells to it? The Adress is BDFB12E8

The tricky part is, you can only modify the amount right when Sid takes some Sea-Shells from you to upgrade your stuff, else you get kicked.

I guess the easiest way to implement it for users would be some lock-checkbox, that then writes the data few times per second while the lock is active, so ppl can upgrade their stuff at sid "for free"

Or is there any other reason you didnt add that?

**Comment by supremetakoyaki** [comment]
No. Editing super sea snails is known to make you an easy target for bans.

if you edited your amount of snails, i would start praying

**Comment by iAroc** [comment]
fair enough. Just as a question, you got any actual reports from ppl that got banned from memory edit in splatoon 3?

**Comment by supremetakoyaki** [comment]
@iAroc 
Hi. Coincidentally, both bans that I know of happened after editing sea snails. One of them also edited salmon run rank and the other one edited their level and experience. Super sea snails were an instaban back in Splatoon 2 so I would assume it's the same here.

Everyone else who's been editing only money, ability chunks and tickets have remained safe for 3 weeks now, but there's still a small risk.

**Comment by iAroc** [comment]
never had problems with edit my super shells in splat 2 tho. well i did edit now my super sea shells in splat3, together with chunks, money and coupons. 
Will keep ya updated if and how long my account survives
