### ISSUE TITLE
Repo license missing

### ISSUE THREAD

**Issue by kwsch** [supremetakoyaki/ShiverBot#5]
Peeking around, noticed your `DecoderUtil` class contains functions that are essentially copied from SysBot.NET's implementation:

https://github.com/supremetakoyaki/ShiverBot/blob/4649cd069a92083c989dd590d1307ced03cc1b4d/Network/DecoderUtil.cs#L20-L31
https://github.com/kwsch/SysBot.NET/blob/6c422c228e21cd93fc2a712ad9f0862b7134c030/SysBot.Base/Util/Decoder.cs#L14-L25

SysBot.NET is licensed under GPLv3, which is a little sticky for attribution / re-licensing, as GPLv3 code is not reusable in other projects that are not licensed under GPLv3 themselves. **Simple fix is to make this repo GPLv3**, as you've not asked me/other SysBot.NET contributors for license exemption. I know it's a small part of the repo, just ensuring the open source repo's license terms are respected :)

Becomes problematic when others fork & modify to [different applications / tools](https://github.com/NatalieWhatever/PvZBFNSysBot), and the original attribution / source is not discoverable.

**Comment by supremetakoyaki** [comment]
Tysm, I added this =)
I actually forgot where I originally took the sys-botbase implementation from because I took it from an ACNH related project around a year ago. and I reused it for ShiverBot.
