### ISSUE TITLE
Version 1.2.1

### ISSUE THREAD

**Issue by Arkkitehti** [supremetakoyaki/ShiverBot#6]
Does shiverbot not work on version 1.2.1?

**Comment by supremetakoyaki** [comment]
Can you please try copying and renaming 44CFD4BD0B42FF96.txt to EF671755F0AF65E3.txt and see if that works?

**Comment by Arkkitehti** [comment]
Thanks, it worked! EF671755F0AF65E5 is the correct one, with 5 in the end instead of 3.
